//定义敏感字集合
const WorldList = new Array();
WorldList.push("4r5e");
WorldList.push("5h1t");
WorldList.push("5hit");
WorldList.push("a55");
WorldList.push("anal");
WorldList.push("anus");
WorldList.push("ar5e");
WorldList.push("arrse");
WorldList.push("arse");
WorldList.push("ass");
WorldList.push("ass-fucker");
WorldList.push("asses");
WorldList.push("assfucker");
WorldList.push("assfukka");
WorldList.push("asshole");
WorldList.push("assholes");
WorldList.push("asswhole");
WorldList.push("a_s_s");
WorldList.push("b!tch");
WorldList.push("b00bs");
WorldList.push("b17ch");
WorldList.push("b1tch");
WorldList.push("ballbag");
WorldList.push("balls");
WorldList.push("ballsack");
WorldList.push("bastard");
WorldList.push("beastial");
WorldList.push("beastiality");
WorldList.push("bellend");
WorldList.push("bestial");
WorldList.push("bestiality");
WorldList.push("bi+ch");
WorldList.push("biatch");
WorldList.push("bitch");
WorldList.push("bitcher");
WorldList.push("bitchers");
WorldList.push("bitches");
WorldList.push("bitchin");
WorldList.push("bitching");
WorldList.push("bloody");
WorldList.push("blow job");
WorldList.push("blowjob");
WorldList.push("blowjobs");
WorldList.push("boiolas");
WorldList.push("bollock");
WorldList.push("bollok");
WorldList.push("boner");
WorldList.push("boob");
WorldList.push("boobs");
WorldList.push("booobs");
WorldList.push("boooobs");
WorldList.push("booooobs");
WorldList.push("booooooobs");
WorldList.push("breasts");
WorldList.push("buceta");
WorldList.push("bugger");
WorldList.push("bum");
WorldList.push("bunny fucker");
WorldList.push("butt");
WorldList.push("butthole");
WorldList.push("buttmuch");
WorldList.push("buttplug");
WorldList.push("c0ck");
WorldList.push("c0cksucker");
WorldList.push("carpet muncher");
WorldList.push("cawk");
WorldList.push("chink");
WorldList.push("cipa");
WorldList.push("cl1t");
WorldList.push("clit");
WorldList.push("clitoris");
WorldList.push("clits");
WorldList.push("cnut");
WorldList.push("cock");
WorldList.push("cock-sucker");
WorldList.push("cockface");
WorldList.push("cockhead");
WorldList.push("cockmunch");
WorldList.push("cockmuncher");
WorldList.push("cocks");
WorldList.push("cocksuck ");
WorldList.push("cocksucked ");
WorldList.push("cocksucker");
WorldList.push("cocksucking");
WorldList.push("cocksucks ");
WorldList.push("cocksuka");
WorldList.push("cocksukka");
WorldList.push("cok");
WorldList.push("cokmuncher");
WorldList.push("coksucka");
WorldList.push("coon");
WorldList.push("cox");
WorldList.push("crap");
WorldList.push("cum");
WorldList.push("cummer");
WorldList.push("cumming");
WorldList.push("cums");
WorldList.push("cumshot");
WorldList.push("cunilingus");
WorldList.push("cunillingus");
WorldList.push("cunnilingus");
WorldList.push("cunt");
WorldList.push("cuntlick ");
WorldList.push("cuntlicker ");
WorldList.push("cuntlicking ");
WorldList.push("cunts");
WorldList.push("cyalis");
WorldList.push("cyberfuc");
WorldList.push("cyberfuck ");
WorldList.push("cyberfucked ");
WorldList.push("cyberfucker");
WorldList.push("cyberfuckers");
WorldList.push("cyberfucking ");
WorldList.push("d1ck");
WorldList.push("damn");
WorldList.push("dick");
WorldList.push("dickhead");
WorldList.push("dildo");
WorldList.push("dildos");
WorldList.push("dink");
WorldList.push("dinks");
WorldList.push("dirsa");
WorldList.push("dlck");
WorldList.push("dog-fucker");
WorldList.push("doggin");
WorldList.push("dogging");
WorldList.push("donkeyribber");
WorldList.push("doosh");
WorldList.push("duche");
WorldList.push("dyke");
WorldList.push("ejaculate");
WorldList.push("ejaculated");
WorldList.push("ejaculates ");
WorldList.push("ejaculating ");
WorldList.push("ejaculatings");
WorldList.push("ejaculation");
WorldList.push("ejakulate");
WorldList.push("f u c k");
WorldList.push("f u c k e r");
WorldList.push("f4nny");
WorldList.push("fag");
WorldList.push("fagging");
WorldList.push("faggitt");
WorldList.push("faggot");
WorldList.push("faggs");
WorldList.push("fagot");
WorldList.push("fagots");
WorldList.push("fags");
WorldList.push("fanny");
WorldList.push("fannyflaps");
WorldList.push("fannyfucker");
WorldList.push("fanyy");
WorldList.push("fatass");
WorldList.push("fcuk");
WorldList.push("fcuker");
WorldList.push("fcuking");
WorldList.push("feck");
WorldList.push("fecker");
WorldList.push("felching");
WorldList.push("fellate");
WorldList.push("fellatio");
WorldList.push("fingerfuck ");
WorldList.push("fingerfucked ");
WorldList.push("fingerfucker ");
WorldList.push("fingerfuckers");
WorldList.push("fingerfucking ");
WorldList.push("fingerfucks ");
WorldList.push("fistfuck");
WorldList.push("fistfucked ");
WorldList.push("fistfucker ");
WorldList.push("fistfuckers ");
WorldList.push("fistfucking ");
WorldList.push("fistfuckings ");
WorldList.push("fistfucks ");
WorldList.push("flange");
WorldList.push("fook");
WorldList.push("fooker");
WorldList.push("fuck");
WorldList.push("fucka");
WorldList.push("fucked");
WorldList.push("fucker");
WorldList.push("fuckers");
WorldList.push("fuckhead");
WorldList.push("fuckheads");
WorldList.push("fuckin");
WorldList.push("fucking");
WorldList.push("fuckings");
WorldList.push("fuckingshitmotherfucker");
WorldList.push("fuckme ");
WorldList.push("fucks");
WorldList.push("fuckwhit");
WorldList.push("fuckwit");
WorldList.push("fudge packer");
WorldList.push("fudgepacker");
WorldList.push("fuk");
WorldList.push("fuker");
WorldList.push("fukker");
WorldList.push("fukkin");
WorldList.push("fuks");
WorldList.push("fukwhit");
WorldList.push("fukwit");
WorldList.push("fux");
WorldList.push("fux0r");
WorldList.push("f_u_c_k");
WorldList.push("gangbang");
WorldList.push("gangbanged ");
WorldList.push("gangbangs ");
WorldList.push("gaylord");
WorldList.push("gaysex");
WorldList.push("goatse");
WorldList.push("God");
WorldList.push("god-dam");
WorldList.push("god-damned");
WorldList.push("goddamn");
WorldList.push("goddamned");
WorldList.push("hardcoresex ");
WorldList.push("hell");
WorldList.push("heshe");
WorldList.push("hoar");
WorldList.push("hoare");
WorldList.push("hoer");
WorldList.push("homo");
WorldList.push("hore");
WorldList.push("horniest");
WorldList.push("horny");
WorldList.push("hotsex");
WorldList.push("jack-off ");
WorldList.push("jackoff");
WorldList.push("jap");
WorldList.push("jerk-off ");
WorldList.push("jism");
WorldList.push("jiz ");
WorldList.push("jizm ");
WorldList.push("jizz");
WorldList.push("kawk");
WorldList.push("knob");
WorldList.push("knobead");
WorldList.push("knobed");
WorldList.push("knobend");
WorldList.push("knobhead");
WorldList.push("knobjocky");
WorldList.push("knobjokey");
WorldList.push("kock");
WorldList.push("kondum");
WorldList.push("kondums");
WorldList.push("kum");
WorldList.push("kummer");
WorldList.push("kumming");
WorldList.push("kums");
WorldList.push("kunilingus");
WorldList.push("l3i+ch");
WorldList.push("l3itch");
WorldList.push("labia");
WorldList.push("lmfao");
WorldList.push("lust");
WorldList.push("lusting");
WorldList.push("m0f0");
WorldList.push("m0fo");
WorldList.push("m45terbate");
WorldList.push("ma5terb8");
WorldList.push("ma5terbate");
WorldList.push("masochist");
WorldList.push("master-bate");
WorldList.push("masterb8");
WorldList.push("masterbat*");
WorldList.push("masterbat3");
WorldList.push("masterbate");
WorldList.push("masterbation");
WorldList.push("masterbations");
WorldList.push("masturbate");
WorldList.push("mo-fo");
WorldList.push("mof0");
WorldList.push("mofo");
WorldList.push("mothafuck");
WorldList.push("mothafucka");
WorldList.push("mothafuckas");
WorldList.push("mothafuckaz");
WorldList.push("mothafucked ");
WorldList.push("mothafucker");
WorldList.push("mothafuckers");
WorldList.push("mothafuckin");
WorldList.push("mothafucking ");
WorldList.push("mothafuckings");
WorldList.push("mothafucks");
WorldList.push("mother fucker");
WorldList.push("motherfuck");
WorldList.push("motherfucked");
WorldList.push("motherfucker");
WorldList.push("motherfuckers");
WorldList.push("motherfuckin");
WorldList.push("motherfucking");
WorldList.push("motherfuckings");
WorldList.push("motherfuckka");
WorldList.push("motherfucks");
WorldList.push("muff");
WorldList.push("mutha");
WorldList.push("muthafecker");
WorldList.push("muthafuckker");
WorldList.push("muther");
WorldList.push("mutherfucker");
WorldList.push("n1gga");
WorldList.push("n1gger");
WorldList.push("nazi");
WorldList.push("nigg3r");
WorldList.push("nigg4h");
WorldList.push("nigga");
WorldList.push("niggah");
WorldList.push("niggas");
WorldList.push("niggaz");
WorldList.push("nigger");
WorldList.push("niggers ");
WorldList.push("nob");
WorldList.push("nob jokey");
WorldList.push("nobhead");
WorldList.push("nobjocky");
WorldList.push("nobjokey");
WorldList.push("numbnuts");
WorldList.push("nutsack");
WorldList.push("orgasim ");
WorldList.push("orgasims ");
WorldList.push("orgasm");
WorldList.push("orgasms ");
WorldList.push("p0rn");
WorldList.push("pawn");
WorldList.push("pecker");
WorldList.push("penis");
WorldList.push("penisfucker");
WorldList.push("phonesex");
WorldList.push("phuck");
WorldList.push("phuk");
WorldList.push("phuked");
WorldList.push("phuking");
WorldList.push("phukked");
WorldList.push("phukking");
WorldList.push("phuks");
WorldList.push("phuq");
WorldList.push("pigfucker");
WorldList.push("pimpis");
WorldList.push("piss");
WorldList.push("pissed");
WorldList.push("pisser");
WorldList.push("pissers");
WorldList.push("pisses ");
WorldList.push("pissflaps");
WorldList.push("pissin ");
WorldList.push("pissing");
WorldList.push("pissoff ");
WorldList.push("poop");
WorldList.push("porn");
WorldList.push("porno");
WorldList.push("pornography");
WorldList.push("pornos");
WorldList.push("prick");
WorldList.push("pricks ");
WorldList.push("pron");
WorldList.push("pube");
WorldList.push("pusse");
WorldList.push("pussi");
WorldList.push("pussies");
WorldList.push("pussy");
WorldList.push("pussys ");
WorldList.push("rectum");
WorldList.push("retard");
WorldList.push("rimjaw");
WorldList.push("rimming");
WorldList.push("s hit");
WorldList.push("s.o.b.");
WorldList.push("sadist");
WorldList.push("schlong");
WorldList.push("screwing");
WorldList.push("scroat");
WorldList.push("scrote");
WorldList.push("scrotum");
WorldList.push("semen");
WorldList.push("sex");
WorldList.push("sh!+");
WorldList.push("sh!t");
WorldList.push("sh1t");
WorldList.push("shag");
WorldList.push("shagger");
WorldList.push("shaggin");
WorldList.push("shagging");
WorldList.push("shemale");
WorldList.push("shi+");
WorldList.push("shit");
WorldList.push("shitdick");
WorldList.push("shite");
WorldList.push("shited");
WorldList.push("shitey");
WorldList.push("shitfuck");
WorldList.push("shitfull");
WorldList.push("shithead");
WorldList.push("shiting");
WorldList.push("shitings");
WorldList.push("shits");
WorldList.push("shitted");
WorldList.push("shitter");
WorldList.push("shitters ");
WorldList.push("shitting");
WorldList.push("shittings");
WorldList.push("shitty ");
WorldList.push("skank");
WorldList.push("slut");
WorldList.push("sluts");
WorldList.push("smegma");
WorldList.push("smut");
WorldList.push("snatch");
WorldList.push("son-of-a-bitch");
WorldList.push("spac");
WorldList.push("spunk");
WorldList.push("s_h_i_t");
WorldList.push("t1tt1e5");
WorldList.push("t1tties");
WorldList.push("teets");
WorldList.push("teez");
WorldList.push("testical");
WorldList.push("testicle");
WorldList.push("tit");
WorldList.push("titfuck");
WorldList.push("tits");
WorldList.push("titt");
WorldList.push("tittie5");
WorldList.push("tittiefucker");
WorldList.push("titties");
WorldList.push("tittyfuck");
WorldList.push("tittywank");
WorldList.push("titwank");
WorldList.push("tosser");
WorldList.push("turd");
WorldList.push("tw4t");
WorldList.push("twat");
WorldList.push("twathead");
WorldList.push("twatty");
WorldList.push("twunt");
WorldList.push("twunter");
WorldList.push("v14gra");
WorldList.push("v1gra");
WorldList.push("vagina");
WorldList.push("viagra");
WorldList.push("vulva");
WorldList.push("w00se");
WorldList.push("wang");
WorldList.push("wank");
WorldList.push("wanker");
WorldList.push("wanky");
WorldList.push("whoar");
WorldList.push("whore");
WorldList.push("willies");
WorldList.push("willy");
WorldList.push("xrated");
WorldList.push("xxx");

module.exports.WorldList = WorldList;